package me.utku.dehabe.enums;

public enum TurkishCity {
    ADANA("Adana"),
    ADIYAMAN("Adiyaman"),
    AFYONKARAHISAR("Afyonkarahisar"),
    AĞRI("Agri"),
    AMASYA("Amasya"),
    ANKARA("Ankara"),
    ANTALYA("Antalya"),
    ARTVİN("Artvin"),
    AYDIN("Aydin"),
    BALIKESİR("Balikesir"),
    BİLECİK("Bilecik"),
    BİNGÖL("Bingol"),
    BİTLİS("Bitlis"),
    BOLU("Bolu"),
    BURDUR("Burdur"),
    BURSA("Bursa"),
    ÇANAKKALE("Canakkale"),
    ÇANKIRI("Cankiri"),
    ÇORUM("Corum"),
    DENİZLİ("Denizli"),
    DİYARBAKIR("Diyarbakir"),
    EDİRNE("Edirne"),
    ELAZIĞ("Elazig"),
    ERZİNCAN("Erzincan"),
    ERZURUM("Erzurum"),
    ESKİŞEHİR("Eskisehir"),
    GAZİANTEP("Gaziantep"),
    GİRESUN("Giresun"),
    GÜMÜŞHANE("Gumushane"),
    HAKKARİ("Hakkari"),
    HATAY("Hatay"),
    ISPARTA("Isparta"),
    MERSİN("Mersin"),
    İSTANBUL("Istanbul"),
    İZMİR("Izmir"),
    KARS("Kars"),
    KASTAMONU("Kastamonu"),
    KAYSERİ("Kayseri"),
    KIRKLARELİ("Kirklareli"),
    KIRŞEHİR("Kirsehir"),
    KOCAELİ("Kocaeli"),
    KONYA("Konya"),
    KÜTAHYA("Kutahya"),
    MALATYA("Malatya"),
    MANİSA("Manisa"),
    KAHRAMANMARAŞ("Kahramanmaras"),
    MARDİN("Mardin"),
    MUĞLA("Mugla"),
    MUŞ("Mus"),
    NEVŞEHİR("Nevsehir"),
    NİĞDE("Nigde"),
    ORDU("Ordu"),
    RİZE("Rize"),
    SAKARYA("Sakarya"),
    SAMSUN("Samsun"),
    SİİRT("Siirt"),
    SİNOP("Sinop"),
    SİVAS("Sivas"),
    TEKİRDAĞ("Tekirdag"),
    TOKAT("Tokat"),
    TRABZON("Trabzon"),
    TUNCELİ("Tunceli"),
    ŞANLIURFA("Sanliurfa"),
    UŞAK("Usak"),
    VAN("Van"),
    YOZGAT("Yozgat"),
    ZONGULDAK("Zonguldak"),
    AKSARAY("Aksaray"),
    BAYBURT("Bayburt"),
    KARAMAN("Karaman"),
    KIRIKKALE("Kirikkale"),
    BATMAN("Batman"),
    ŞIRNAK("Sirnak"),
    BARTIN("Bartin"),
    ARDAHAN("Ardahan"),
    IĞDIR("Igdir"),
    YALOVA("Yalova"),
    KARABÜK("Karabuk"),
    KİLİS("Kilis"),
    OSMANİYE("Osmaniye"),
    DÜZCE("Duzce");

    private final String name;

    TurkishCity(String name) {
        this.name = name;
    }

    public String getName() {
        return name;
    }
}

